apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: 905418425077.dkr.ecr.ap-south-1.amazonaws.com/preprod-petclinic:005dee1-20
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: app-config-prod
              key: MYSQL_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: prod-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prod-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: prod-secrets
              key: MYSQL_DATABASE
